# Your presentation title
title: 'Embracing the nocode movement and creating an online portfolio'


# Your presentation description (optional)
description: 'Gladden Podcast, Saturday April 18, 2020 7:00PM, hosted by D. Garmondyu Whorway with guest Adam DJ Brett'

# Your name (optional)
author: 'Adam DJ Brett'

# The Reveal theme
reveal_theme: black.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/

# Additional custom CSS paths
extra_css:

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet:

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options:

# Additional reveal.js dependencies
reveal_dependencies:

# Reveal.js subdirectory
reveal_path: reveal.js/

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - LICENSE
  - README.md

# Don't change anything below
markdown: kramdown
highlighter: rouge
markdown_ext: ignoreme
